apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=drlraj
resources:
  - mysql-deployment.yml
  - nc-deployment.yaml
  - create-storage.yml
  - role_binding.yml
  - service.yml
  - efs_provisinor.yml

 
